BEGIN TRANSACTION
DROP TABLE IF EXISTS STUDENTS, COURSES, REGISTRATION, TEACHERS;

CREATE TABLE STUDENTS(
student_id INT NOT NULL IDENTITY PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
date_of_birth DATE NOT NULL,
major VARCHAR(100) NOT NULL,
CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id)
);

CREATE TABLE COURSES(
course_id serial,
course_code VARCHAR(10) UNIQUE NOT NULL,
course_description VARCHAR(500) NOT NULL,
course_name VARCHAR(100) NOT NULL,
numb_credit INT NOT NULL,
CONSTRAINT PK_COURSES PRIMARY KEY (course_id)

);

CREATE TABLE REGISTRATION(
    registration_id serial,
    student_id INT NOT NULL ,
    semester VARCHAR(50) NOT NULL,
    CONSTRAINT PK_REGISTRATION PRIMARY KEY (registration_id),
    CONSTRAINT FK_REGISTRATION_STUDENTS FOREIGN KEY (student_id) REFERENCES STUDENTS(student_id)
);

CREATE TABLE TEACHERS (
    teacher_id serial,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    course_teach VARCHAR(50) NOT NULL,
    course_code VARCHAR(10) NOT NULL,
    CONSTRAINT PK_TEACHERS PRIMARY KEY (teacher_id),
    CONSTRAINT FK_TEACHERS_COURSES FOREIGN KEY (course_code) REFERENCES COURSES (course_code)

);


COMMIT TRANSACTION;